Inmobiliaria/Models/LoginView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Inmobiliaria.Models
{
    public class LoginView
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Mail { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Clave { get; set; }
    }
}

Inmobiliaria/Controllers/GarantesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Inmobiliaria.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace Inmobiliaria.Controllers
{
    [Authorize]
    public class GarantesController : Controller
    {
        private readonly IConfiguration configuration;
        private readonly RepositorioGarante repositorioGarante;

        public GarantesController(IConfiguration configuration)
        {

            this.configuration = configuration;
            repositorioGarante = new RepositorioGarante(configuration);
        }
        // GET: Garantes
        public ActionResult Index()
        {
            var lista = repositorioGarante.ObtenerTodos();
            return View(lista);
        }

        // GET: Garantes/Details/5
        public ActionResult Details(int id)
        {
            var g = repositorioGarante.ObtenerPorId(id);
            return View(g);
        }

        // GET: Garantes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Garantes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Garante g)
        {
            try
            {
                // TODO: Add insert logic here
                int res = repositorioGarante.Alta(g);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Garantes/Edit/5
        public ActionResult Edit(int id)
        {
            var g = repositorioGarante.ObtenerPorId(id);
            return View(g);
        }

        // POST: Garantes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Garante g)
        {
            try
            {
                // TODO: Add update logic here
                g.IdGarante = id;
                int res = repositorioGarante.Modificacion(g);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        [Authorize(Policy = "Administrador")]
        // GET: Garantes/Delete/5
        public ActionResult Delete(int id)
        {
            var g = repositorioGarante.ObtenerPorId(id);
            return View(g);
        }

        // POST: Garantes/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Garante g)
        {
            try 
            {
                // TODO: Add delete logic here
                
                int r=repositorioGarante.Baja(id);
                 
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Inmobiliaria/Controllers/PagosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Inmobiliaria.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace Inmobiliaria.Controllers
{
    [Authorize]
    public class PagosController : Controller
    {
        private readonly IConfiguration configuration;
        private readonly RepositorioPago repositorioPago;
        private readonly RepositorioInquilino repositorioInquilino;
        private readonly RepositorioContrato repositorioContrato;
        private readonly RepositorioInmueble  repositorioInmueble;


        public PagosController(IConfiguration configuration)
        {
            this.configuration = configuration;
            repositorioPago = new RepositorioPago(configuration);
            repositorioInquilino = new RepositorioInquilino(configuration);
            repositorioContrato = new RepositorioContrato(configuration);
            repositorioInmueble = new RepositorioInmueble(configuration);
        }
        // GET: Pagos
        public ActionResult Index()
        {
            try
            {
                var lista = repositorioPago.ObtenerTodos();
                return View(lista);

            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View();
            }

        }

        public ActionResult BuscarInquilinoModal() 
        {
            return View("_BuscarInquilino",new Inquilino());
        }

       
        // GET: Pagos/Details/5
        public ActionResult Details(int id)
        {
            var i = repositorioPago.ObtenerPorId(id);
            return View(i);
        }
        public ActionResult BuscarContrato()
        {
            List<Contrato> contrato = new List<Contrato>(); 
            return View(contrato);
        }

        // POST: Pagos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BuscarContrato(BusquedaContrato busqueda)
        {
            try
            {
                // TODO: Add insert logic here


                var res = repositorioContrato.ObtenerPorDni(busqueda.Dni);

                return View(res);
            }
            catch(Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }

        // GET: Pagos/Create
        public ActionResult CrearPago(int id)
        {
            var contrato = repositorioContrato.ObtenerPorId(id);
            var inmueble = repositorioInmueble.ObtenerPorId(contrato.IdInmueble);
            var cantidadPagos = repositorioPago.ObtenerCantidadPagos(contrato.IdContrato);
            ViewData["importe"] = inmueble.Precio;
            ViewData["IdContrato"] = contrato.IdContrato;
            ViewData["NumeroPago"] = cantidadPagos + 1 ;
            return View();
        }

        // POST: Pagos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CrearPago(Pago p)
        {
            try
            {
                // TODO: Add insert logic here
                int res = repositorioPago.Alta(p);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Pagos/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: Pagos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pago p)
        {
            try
            {
                // TODO: Add insert logic here
                int res = repositorioPago.Alta(p);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Pagos/Edit/5
        public ActionResult Edit(int id)
        {
            var p = repositorioPago.ObtenerPorId(id);
            return View(p);
        }

        // POST: Pagos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Pago p)
        {
            try
            {
                // TODO: Add update logic here
                p.IdPago = id;
                int res = repositorioPago.Modificacion(p);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        [Authorize(Policy = "Administrador")]
        // GET: Pagos/Delete/5
        public ActionResult Delete(int id)
        {
            var lista = repositorioPago.ObtenerPorId(id); 
            return View(lista);
        }

        // POST: Pagos/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Pago pago)
        {
            try
            {
                // TODO: Add delete logic here
                int res = repositorioPago.Baja(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Inmobiliaria/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Inmobiliaria.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace Inmobiliaria.Controllers
{
    
    public class UsuariosController : Controller
    {
        private readonly IConfiguration configuration;
        private readonly RepositorioUsuario repositorioUsuario;


        public UsuariosController(IConfiguration configuration)
        {
            this.configuration = configuration;
            repositorioUsuario = new RepositorioUsuario(configuration);
            
        }



        [Authorize(Policy = "Administrador")]
        // GET: Usuarios
        public ActionResult Index()
        {
            var lista = repositorioUsuario.ObtenerTodos();
            return View(lista);
        }
        

        // GET: Usuarios/Details/5
        public ActionResult Details(int id)
        {
            var u = repositorioUsuario.ObtenerPorId(id);
            return View(u);
        }

        [AllowAnonymous]
        // GET: Usuarios/Create
        public ActionResult Create()
        {
            return View();
        }

        [AllowAnonymous]
        // POST: Usuarios/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Usuario u)
        {
            try
            {
                // TODO: Add insert logic here
                u.Estado = "1";
                string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                    password: u.Clave,
                    salt: System.Text.Encoding.ASCII.GetBytes(configuration["Salt"]),
                    prf: KeyDerivationPrf.HMACSHA1,
                    iterationCount: 1000,
                    numBytesRequested: 256 / 8));
                u.Clave = hashed;
                int res = repositorioUsuario.Alta(u);
                
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Usuarios/Edit/5
        public ActionResult Edit(int id)
        {
            var u = repositorioUsuario.ObtenerPorId(id);
            return View(u);
        }

        // POST: Usuarios/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Usuario u)
        {
            try
            {
                // TODO: Add update logic here
                u.IdUsuario = id;
                int res=repositorioUsuario.Modificacion(u);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Usuarios/Delete/5
        [Authorize(Policy ="Administrador")]
        public ActionResult Delete(int id)
        {
            var usuario = repositorioUsuario.ObtenerPorId(id);
            
            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost]
        
        
        public ActionResult Delete(int id, Usuario usuario)
        {
            Usuario u = null;
            try
            {
                // TODO: Add delete logic here
                u = repositorioUsuario.ObtenerPorId(id); 
                u.Estado = "0";
                int res = repositorioUsuario.BajaLogica(u);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }
        [AllowAnonymous]
        // GET: Usuarios/Login/
        public ActionResult Login()
        {

            return View();


        }

        // POST: Home/Login
        [AllowAnonymous]
        [HttpPost]
        
        public async Task<ActionResult> Login(LoginView login)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    string hashed = Convert.ToBase64String(KeyDerivation.Pbkdf2(
                    password: login.Clave,
                    salt: System.Text.Encoding.ASCII.GetBytes(configuration["Salt"]),
                    prf: KeyDerivationPrf.HMACSHA1,
                    iterationCount: 1000,
                    numBytesRequested: 256 / 8));

                    var e = repositorioUsuario.ObtenerPorEmail(login.Mail);

                    if (e == null || e.Clave != hashed)
                    {
                        //ViewBag.Mensaje = "Mail o Contraseña Incorrectos";
                        ModelState.AddModelError("", "El mail o la clave son incorrectos");
                        return View();
                    }
                    var claim = new List<Claim>
                    {
                    new Claim(ClaimTypes.Name, e.Mail),
                    new Claim("FullName", e.Nombre + " " + e.Apellido),

                    new Claim(ClaimTypes.Role, e.Rol),
                     };

                    var claimsIdentity = new ClaimsIdentity(
                    claim, CookieAuthenticationDefaults.AuthenticationScheme);

                    await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity));

                    return RedirectToAction("Index","Home");
                }
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View();
            }
        }


        // GET: Home/Login
        public async Task<ActionResult> Logout()
        {
            await HttpContext.SignOutAsync(
                CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index","Home");
        }
    }
}

Inmobiliaria/Views/Shared/_BuscarInquilino.cshtml
<div class="modal" tabindex="-1" role="dialog" id="modal_BuscarInquilino">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Buscador Inquilino</h5>
                <h5 class="modal-title">Ingrese DNI</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-action="BuscarI">
                    <div class="form-group">
                        
                        <input type="text" class="form-control" name="buscarDni">
                        <input type="submit" name="buscar" value="buscar" />
                    </div>
                </form>
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Buscar</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

Inmobiliaria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inmobiliaria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        .mynav_navbar {
            overflow: hidden;
            background-color: #333;
        }

            .mynav_navbar a {
                float: left;
                font-size: 16px;
                color: white;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }

        .mynav_dropdown {
            float: left;
            overflow: hidden;
        }

            .mynav_dropdown .mynav_dropbtn {
                font-size: 16px;
                border: none;
                outline: none;
                color: white;
                padding: 14px 16px;
                background-color: inherit;
                font-family: inherit;
                margin: 0;
            }

            .mynav_navbar a:hover, .mynav_dropdown:hover .mynav_dropbtn {
                background-color: red;
            }

        .mynav_dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .mynav_dropdown-content a {
                float: none;
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
                text-align: left;
            }

                .mynav_dropdown-content a:hover {
                    background-color: #ddd;
                }

        .mynav_dropdown:hover .mynav_dropdown-content {
            display: block;
        }
    </style>

</head>

<body >

    @if (!User.Identity.IsAuthenticated)
    {
         <partial name = "_Login.cshtml" />

        //<a asp-controller="Usuarios" asp-action="Login"></a>
    }
    else {

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inmobiliaria</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                <div class="mynav_navbar">
                    <a asp-controller="Home" asp-action="Index">Home</a>
                    <a asp-controller="Propietarios" asp-action="Index">Propietarios</a>
                    <a asp-controller="Inquilinos" asp-action="Index">Inquilinos</a>
                    <a asp-controller="Inmuebles" asp-action="Index">Inmuebles</a>
                    <a asp-controller="Pagos" asp-action="Index">Pagos</a>
                    <a asp-controller="Garantes" asp-action="Index">Garantes</a>
                    <a asp-controller="Contratos" asp-action="Index">Contratos</a>
                    <a asp-controller="Usuarios" asp-action="Index">Usuarios</a>


                    <a asp-controller="Usuarios" asp-action="Logout">Salir</a>
                    <div class="mynav_dropdown">
                        <button class="mynav_dropbtn">
                            Perfil
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="mynav_dropdown-content">
                            <a>HOLA @(User.Identity.IsAuthenticated?User.Claims.First(x=>x.Type =="FullName").Value:"")</a>
                            <a asp-controller="Home" asp-action="Privacy">Privacy</a>
                            <a href="#">Perfil</a>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>
    
    }

    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Inmobiliaria - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Inmobiliaria/Views/Shared/_Login.cshtml
@model Inmobiliaria.Models.LoginView

@{
    ViewData["Title"] = "Login";
}

    
    <div class="row align-items-center justify-content-center vh-100">
        <div class="col-md-4">
            <h1>Login</h1>
            <h4>Datos de Acceso</h4>

            
            <form asp-action="Login" asp-controller="Usuarios">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Mail" class="control-label"></label>
                    <input asp-for="Mail" class="form-control" />
                    <span asp-validation-for="Mail" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Clave" class="control-label"></label>
                    <input asp-for="Clave" class="form-control" />
                    <span asp-validation-for="Clave" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Ingresar" class="btn btn-primary" />
                   
                </div>
            </form>

        </div>
       
    </div>
<div>
   
</div>


@await Html.PartialAsync("_ValidationScriptsPartial")

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@